quotes = [
"The man who passes the sentence should swing the sword.",
"You grew up with actors - you learned their craft and you learned it well. But I grew up with soldiers. I learned how to die a long time ago ",
"The Robert I grew up with didn't tremble at the shadow of an unborn child.",
"Do you have a shred of honor?",
"If the day ever comes when that boy would rather wield a sword than forge one, you send him to me.",
"Winter is coming!",
"War is easier than daughters.",
"If you're going to own a sword, you'd better know how to use it!",
"Is that what you tell yourself at night? You're a servant of justice?",
"I followed you into war, twice, without doubts, without second thoughts. But I will not follow you now",
"A madman sees what he sees",
"I'll fear the Dothraki the day they teach their horses to run on water.",
"You want me to serve the woman who murdered my King, who butchered my man, who crippled my son?",
"I, Eddard of the house Stark, lord of Winterfell and warden of the North, sentence you to die.",
"There's great honor serving in the night's watch. The Starks have manned the wall for thousands of years.",
"Why is it always the innocents who suffer most, when you high lords play your game of thrones?",
"The only time a man can be brave is when he is afraid.",
"You think my life is some precious thing to me?",
"I don't fight in tournaments because when I fight a man for real, I don't want him to know what I can do.",
"You may not have my name, but you have my blood.",
"I'm glad we never met on the field, Ser Barristan. As is my wife. I don't think the widow's life would suit her.",
"I thought you were a better man."
]
